// <auto-generated />
namespace AssetSqlDatabase.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AssetEntryAdditionalTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssetEntryAdditionalTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710100910211_AssetEntryAdditionalTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
